### ISSUE TITLE
App crashes in launch screen if location permission not granted.

### ISSUE THREAD

**Issue by kevalpatel2106** [mohak1712/UberUX#3]
Application crashes on the first launch as there is no location permission available. Ideally, the application should check for location permission and ask the user to grant location permission if not granted before calling ` mMap.setMyLocationEnabled(true);`.  According to Google Maps Doc, before [GoogleMap#setMyLocationEnabled()](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setMyLocationEnabled(boolean)) you need to request permission for either ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION .

Crash log: 
```
FATAL EXCEPTION: main
Process: mohak.uberux, PID: 27420
java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION
at com.google.maps.api.android.lib6.impl.az.c(:com.google.android.gms.DynamiteModulesB:675)
at com.google.android.gms.maps.internal.k.onTransact(:com.google.android.gms.DynamiteModulesB:141)
at android.os.Binder.transact(Binder.java:499)
at com.google.android.gms.internal.zzed.zzb(Unknown Source)
at com.google.android.gms.maps.internal.zzg.setMyLocationEnabled(Unknown Source)
at com.google.android.gms.maps.GoogleMap.setMyLocationEnabled(Unknown Source)
at mohak.uberux.BaseActivity.onMapReady(BaseActivity.java:91)
at mohak.uberux.MapActivity.onMapReady(MapActivity.java:221)
at com.google.android.gms.maps.zzaj.zza(Unknown Source)
at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source)
at android.os.Binder.transact(Binder.java:499)
at gl.b(:com.google.android.gms.DynamiteModulesB:20)
at com.google.android.gms.maps.internal.bf.a(:com.google.android.gms.DynamiteModulesB:5)
at com.google.maps.api.android.lib6.impl.bb.run(:com.google.android.gms.DynamiteModulesB:5)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:6274)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mohak1712** [comment]
There are no runtime permission checks anywhere. Ideally, it should be present but the focus here was on animations only !

**Comment by kevalpatel2106** [comment]
@mohak1712 But application is getting a crash because of that whenever I run for the first time. 😊 
I generated PR #4  that contains the fix.
